/**
 * Supabase Database Types - Auto-generated from schema.sql
 *
 * DO NOT EDIT THIS FILE MANUALLY!
 *
 * This file is generated by running:
 *   npm run db:types
 *
 * Which executes:
 *   npx supabase gen types typescript --local > src/types/generated.ts
 *
 * The CI workflow will fail if this file is out of sync with schema.sql.
 * After modifying schema.sql, regenerate this file and commit both together.
 *
 * @see https://supabase.com/docs/reference/cli/supabase-gen-types-typescript
 */

// ============================================================================
// PLACEHOLDER TYPES - Replace with actual Supabase-generated types
// ============================================================================
// When you run `npm run db:types` against a live Supabase instance or local
// database, this file will be replaced with the actual generated types.
// The types below are placeholder definitions that match the schema.sql
// structure to allow the codebase to compile before generation.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = {
  public: {
    Tables: {
      // ======================================================================
      // COURSE STRUCTURE TABLES
      // ======================================================================
      courses: {
        Row: {
          id: number;
          slug: string;
          title: string;
          description: string | null;
          thumbnail_url: string | null;
          track: 'animal_advocacy' | 'climate' | 'ai_safety' | 'general' | null;
          difficulty: 'beginner' | 'intermediate' | 'advanced' | null;
          is_published: boolean;
          is_cohort_based: boolean;
          default_duration_weeks: number;
          enrollment_type: 'open' | 'cohort_only' | 'hybrid';
          created_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: number;
          slug: string;
          title: string;
          description?: string | null;
          thumbnail_url?: string | null;
          track?: 'animal_advocacy' | 'climate' | 'ai_safety' | 'general' | null;
          difficulty?: 'beginner' | 'intermediate' | 'advanced' | null;
          is_published?: boolean;
          is_cohort_based?: boolean;
          default_duration_weeks?: number;
          enrollment_type?: 'open' | 'cohort_only' | 'hybrid';
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: number;
          slug?: string;
          title?: string;
          description?: string | null;
          thumbnail_url?: string | null;
          track?: 'animal_advocacy' | 'climate' | 'ai_safety' | 'general' | null;
          difficulty?: 'beginner' | 'intermediate' | 'advanced' | null;
          is_published?: boolean;
          is_cohort_based?: boolean;
          default_duration_weeks?: number;
          enrollment_type?: 'open' | 'cohort_only' | 'hybrid';
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      modules: {
        Row: {
          id: number;
          course_id: number;
          title: string;
          description: string | null;
          order_index: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: number;
          course_id: number;
          title: string;
          description?: string | null;
          order_index: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: number;
          course_id?: number;
          title?: string;
          description?: string | null;
          order_index?: number;
          created_at?: string;
          updated_at?: string;
        };
      };
      lessons: {
        Row: {
          id: number;
          module_id: number;
          title: string;
          slug: string;
          content: string | null;
          video_url: string | null;
          duration_minutes: number | null;
          order_index: number;
          is_preview: boolean;
          resources: Json;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: number;
          module_id: number;
          title: string;
          slug: string;
          content?: string | null;
          video_url?: string | null;
          duration_minutes?: number | null;
          order_index: number;
          is_preview?: boolean;
          resources?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: number;
          module_id?: number;
          title?: string;
          slug?: string;
          content?: string | null;
          video_url?: string | null;
          duration_minutes?: number | null;
          order_index?: number;
          is_preview?: boolean;
          resources?: Json;
          created_at?: string;
          updated_at?: string;
        };
      };

      // ======================================================================
      // COHORT SYSTEM TABLES
      // ======================================================================
      cohorts: {
        Row: {
          id: string; // UUID
          course_id: number;
          name: string;
          start_date: string;
          end_date: string | null;
          status: 'upcoming' | 'active' | 'completed' | 'archived';
          max_students: number | null;
          created_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          course_id: number;
          name: string;
          start_date: string;
          end_date?: string | null;
          status?: 'upcoming' | 'active' | 'completed' | 'archived';
          max_students?: number | null;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          course_id?: number;
          name?: string;
          start_date?: string;
          end_date?: string | null;
          status?: 'upcoming' | 'active' | 'completed' | 'archived';
          max_students?: number | null;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      cohort_enrollments: {
        Row: {
          id: string; // UUID
          cohort_id: string;
          user_id: string;
          enrolled_at: string;
          status: 'active' | 'completed' | 'dropped' | 'paused';
          completed_lessons: number;
          progress: Json;
          last_activity_at: string;
        };
        Insert: {
          id?: string;
          cohort_id: string;
          user_id: string;
          enrolled_at?: string;
          status?: 'active' | 'completed' | 'dropped' | 'paused';
          completed_lessons?: number;
          progress?: Json;
          last_activity_at?: string;
        };
        Update: {
          id?: string;
          cohort_id?: string;
          user_id?: string;
          enrolled_at?: string;
          status?: 'active' | 'completed' | 'dropped' | 'paused';
          completed_lessons?: number;
          progress?: Json;
          last_activity_at?: string;
        };
      };
      cohort_schedules: {
        Row: {
          id: string; // UUID
          cohort_id: string;
          module_id: number;
          unlock_date: string;
          lock_date: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          cohort_id: string;
          module_id: number;
          unlock_date: string;
          lock_date?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          cohort_id?: string;
          module_id?: number;
          unlock_date?: string;
          lock_date?: string | null;
          created_at?: string;
        };
      };
      lesson_progress: {
        Row: {
          id: number;
          user_id: string;
          lesson_id: number;
          cohort_id: string | null;
          completed: boolean;
          completed_at: string | null;
          video_position_seconds: number;
          time_spent_seconds: number;
          watch_count: number;
          last_accessed_at: string;
          created_at: string;
        };
        Insert: {
          id?: number;
          user_id: string;
          lesson_id: number;
          cohort_id?: string | null;
          completed?: boolean;
          completed_at?: string | null;
          video_position_seconds?: number;
          time_spent_seconds?: number;
          watch_count?: number;
          last_accessed_at?: string;
          created_at?: string;
        };
        Update: {
          id?: number;
          user_id?: string;
          lesson_id?: number;
          cohort_id?: string | null;
          completed?: boolean;
          completed_at?: string | null;
          video_position_seconds?: number;
          time_spent_seconds?: number;
          watch_count?: number;
          last_accessed_at?: string;
          created_at?: string;
        };
      };
      enrollments: {
        Row: {
          id: number;
          user_id: string;
          course_id: number;
          cohort_id: string | null;
          enrolled_at: string;
          completed_at: string | null;
          status: 'active' | 'completed' | 'dropped' | 'paused';
          progress_percentage: number;
        };
        Insert: {
          id?: number;
          user_id: string;
          course_id: number;
          cohort_id?: string | null;
          enrolled_at?: string;
          completed_at?: string | null;
          status?: 'active' | 'completed' | 'dropped' | 'paused';
          progress_percentage?: number;
        };
        Update: {
          id?: number;
          user_id?: string;
          course_id?: number;
          cohort_id?: string | null;
          enrolled_at?: string;
          completed_at?: string | null;
          status?: 'active' | 'completed' | 'dropped' | 'paused';
          progress_percentage?: number;
        };
      };

      // ======================================================================
      // QUIZ TABLES
      // ======================================================================
      quizzes: {
        Row: {
          id: string; // UUID
          course_id: number;
          module_id: number | null;
          lesson_id: number | null;
          title: string;
          description: string | null;
          time_limit_minutes: number | null;
          passing_score: number;
          max_attempts: number;
          randomize_questions: boolean;
          show_correct_answers: boolean;
          show_results_immediately: boolean;
          is_published: boolean;
          available_from: string | null;
          available_until: string | null;
          created_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          course_id: number;
          module_id?: number | null;
          lesson_id?: number | null;
          title: string;
          description?: string | null;
          time_limit_minutes?: number | null;
          passing_score?: number;
          max_attempts?: number;
          randomize_questions?: boolean;
          show_correct_answers?: boolean;
          show_results_immediately?: boolean;
          is_published?: boolean;
          available_from?: string | null;
          available_until?: string | null;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          course_id?: number;
          module_id?: number | null;
          lesson_id?: number | null;
          title?: string;
          description?: string | null;
          time_limit_minutes?: number | null;
          passing_score?: number;
          max_attempts?: number;
          randomize_questions?: boolean;
          show_correct_answers?: boolean;
          show_results_immediately?: boolean;
          is_published?: boolean;
          available_from?: string | null;
          available_until?: string | null;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      quiz_questions: {
        Row: {
          id: string; // UUID
          quiz_id: string;
          question_type: 'multiple_choice' | 'true_false' | 'short_answer' | 'essay' | 'multiple_select';
          question_text: string;
          points: number;
          order_index: number;
          options: Json | null;
          correct_answer: string | null;
          answer_explanation: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          quiz_id: string;
          question_type: 'multiple_choice' | 'true_false' | 'short_answer' | 'essay' | 'multiple_select';
          question_text: string;
          points?: number;
          order_index: number;
          options?: Json | null;
          correct_answer?: string | null;
          answer_explanation?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          quiz_id?: string;
          question_type?: 'multiple_choice' | 'true_false' | 'short_answer' | 'essay' | 'multiple_select';
          question_text?: string;
          points?: number;
          order_index?: number;
          options?: Json | null;
          correct_answer?: string | null;
          answer_explanation?: string | null;
          created_at?: string;
        };
      };
      quiz_attempts: {
        Row: {
          id: string; // UUID
          quiz_id: string;
          user_id: string;
          cohort_id: string | null;
          attempt_number: number;
          started_at: string;
          submitted_at: string | null;
          time_taken_seconds: number | null;
          score: number | null;
          total_points: number | null;
          points_earned: number | null;
          passed: boolean | null;
          answers_json: Json;
          grading_status: 'pending' | 'auto_graded' | 'needs_review';
          graded_by: string | null;
          graded_at: string | null;
        };
        Insert: {
          id?: string;
          quiz_id: string;
          user_id: string;
          cohort_id?: string | null;
          attempt_number: number;
          started_at?: string;
          submitted_at?: string | null;
          time_taken_seconds?: number | null;
          score?: number | null;
          total_points?: number | null;
          points_earned?: number | null;
          passed?: boolean | null;
          answers_json?: Json;
          grading_status?: 'pending' | 'auto_graded' | 'needs_review';
          graded_by?: string | null;
          graded_at?: string | null;
        };
        Update: {
          id?: string;
          quiz_id?: string;
          user_id?: string;
          cohort_id?: string | null;
          attempt_number?: number;
          started_at?: string;
          submitted_at?: string | null;
          time_taken_seconds?: number | null;
          score?: number | null;
          total_points?: number | null;
          points_earned?: number | null;
          passed?: boolean | null;
          answers_json?: Json;
          grading_status?: 'pending' | 'auto_graded' | 'needs_review';
          graded_by?: string | null;
          graded_at?: string | null;
        };
      };

      // ======================================================================
      // ASSIGNMENT TABLES
      // ======================================================================
      assignments: {
        Row: {
          id: string; // UUID
          course_id: number;
          module_id: number | null;
          lesson_id: number | null;
          title: string;
          description: string | null;
          instructions: string | null;
          max_points: number;
          due_date: string | null;
          allow_late_submissions: boolean;
          late_penalty_percent: number;
          allow_resubmission: boolean;
          max_submissions: number;
          max_file_size_mb: number;
          allowed_file_types: string[];
          is_published: boolean;
          created_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          course_id: number;
          module_id?: number | null;
          lesson_id?: number | null;
          title: string;
          description?: string | null;
          instructions?: string | null;
          max_points?: number;
          due_date?: string | null;
          allow_late_submissions?: boolean;
          late_penalty_percent?: number;
          allow_resubmission?: boolean;
          max_submissions?: number;
          max_file_size_mb?: number;
          allowed_file_types?: string[];
          is_published?: boolean;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          course_id?: number;
          module_id?: number | null;
          lesson_id?: number | null;
          title?: string;
          description?: string | null;
          instructions?: string | null;
          max_points?: number;
          due_date?: string | null;
          allow_late_submissions?: boolean;
          late_penalty_percent?: number;
          allow_resubmission?: boolean;
          max_submissions?: number;
          max_file_size_mb?: number;
          allowed_file_types?: string[];
          is_published?: boolean;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      assignment_submissions: {
        Row: {
          id: string; // UUID
          assignment_id: string;
          user_id: string;
          submission_number: number;
          submission_text: string | null;
          file_url: string | null;
          file_name: string | null;
          file_size_bytes: number | null;
          file_type: string | null;
          file_urls: string[] | null;
          submitted_at: string;
          is_late: boolean;
          status: 'draft' | 'submitted' | 'graded' | 'returned';
          score: number | null;
          feedback: string | null;
          graded_by: string | null;
          graded_at: string | null;
          rubric_scores: Json | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          assignment_id: string;
          user_id: string;
          submission_number?: number;
          submission_text?: string | null;
          file_url?: string | null;
          file_name?: string | null;
          file_size_bytes?: number | null;
          file_type?: string | null;
          file_urls?: string[] | null;
          submitted_at?: string;
          is_late?: boolean;
          status?: 'draft' | 'submitted' | 'graded' | 'returned';
          score?: number | null;
          feedback?: string | null;
          graded_by?: string | null;
          graded_at?: string | null;
          rubric_scores?: Json | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          assignment_id?: string;
          user_id?: string;
          submission_number?: number;
          submission_text?: string | null;
          file_url?: string | null;
          file_name?: string | null;
          file_size_bytes?: number | null;
          file_type?: string | null;
          file_urls?: string[] | null;
          submitted_at?: string;
          is_late?: boolean;
          status?: 'draft' | 'submitted' | 'graded' | 'returned';
          score?: number | null;
          feedback?: string | null;
          graded_by?: string | null;
          graded_at?: string | null;
          rubric_scores?: Json | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      assignment_rubrics: {
        Row: {
          id: string; // UUID
          assignment_id: string;
          criterion: string;
          description: string | null;
          max_points: number;
          order_index: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          assignment_id: string;
          criterion: string;
          description?: string | null;
          max_points: number;
          order_index: number;
          created_at?: string;
        };
        Update: {
          id?: string;
          assignment_id?: string;
          criterion?: string;
          description?: string | null;
          max_points?: number;
          order_index?: number;
          created_at?: string;
        };
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      is_admin: {
        Args: { user_uuid?: string };
        Returns: boolean;
      };
      is_teacher: {
        Args: { user_uuid?: string };
        Returns: boolean;
      };
      can_user_submit: {
        Args: { assignment_id_param: string; user_id_param: string };
        Returns: boolean;
      };
      get_assignment_stats: {
        Args: { assignment_id_param: string };
        Returns: {
          total_submissions: number;
          graded_submissions: number;
          average_score: number;
          late_submissions: number;
          on_time_submissions: number;
        }[];
      };
      enroll_in_cohort: {
        Args: { p_cohort_id: string; p_user_id: string };
        Returns: Database['public']['Tables']['cohort_enrollments']['Row'];
      };
    };
    Enums: {
      [_ in never]: never;
    };
    CompositeTypes: {
      [_ in never]: never;
    };
  };
};

// ============================================================================
// HELPER TYPES - Convenience aliases for common table types
// ============================================================================

/** Row type for courses table */
export type CourseRow = Database['public']['Tables']['courses']['Row'];
export type CourseInsert = Database['public']['Tables']['courses']['Insert'];
export type CourseUpdate = Database['public']['Tables']['courses']['Update'];

/** Row type for modules table */
export type ModuleRow = Database['public']['Tables']['modules']['Row'];
export type ModuleInsert = Database['public']['Tables']['modules']['Insert'];
export type ModuleUpdate = Database['public']['Tables']['modules']['Update'];

/** Row type for lessons table */
export type LessonRow = Database['public']['Tables']['lessons']['Row'];
export type LessonInsert = Database['public']['Tables']['lessons']['Insert'];
export type LessonUpdate = Database['public']['Tables']['lessons']['Update'];

/** Row type for cohorts table */
export type CohortRow = Database['public']['Tables']['cohorts']['Row'];
export type CohortInsert = Database['public']['Tables']['cohorts']['Insert'];
export type CohortUpdate = Database['public']['Tables']['cohorts']['Update'];

/** Row type for cohort_enrollments table */
export type CohortEnrollmentRow = Database['public']['Tables']['cohort_enrollments']['Row'];
export type CohortEnrollmentInsert = Database['public']['Tables']['cohort_enrollments']['Insert'];
export type CohortEnrollmentUpdate = Database['public']['Tables']['cohort_enrollments']['Update'];

/** Row type for lesson_progress table */
export type LessonProgressRow = Database['public']['Tables']['lesson_progress']['Row'];
export type LessonProgressInsert = Database['public']['Tables']['lesson_progress']['Insert'];
export type LessonProgressUpdate = Database['public']['Tables']['lesson_progress']['Update'];

/** Row type for enrollments table */
export type EnrollmentRow = Database['public']['Tables']['enrollments']['Row'];
export type EnrollmentInsert = Database['public']['Tables']['enrollments']['Insert'];
export type EnrollmentUpdate = Database['public']['Tables']['enrollments']['Update'];

/** Row type for quizzes table */
export type QuizRow = Database['public']['Tables']['quizzes']['Row'];
export type QuizInsert = Database['public']['Tables']['quizzes']['Insert'];
export type QuizUpdate = Database['public']['Tables']['quizzes']['Update'];

/** Row type for quiz_questions table */
export type QuizQuestionRow = Database['public']['Tables']['quiz_questions']['Row'];
export type QuizQuestionInsert = Database['public']['Tables']['quiz_questions']['Insert'];
export type QuizQuestionUpdate = Database['public']['Tables']['quiz_questions']['Update'];

/** Row type for quiz_attempts table */
export type QuizAttemptRow = Database['public']['Tables']['quiz_attempts']['Row'];
export type QuizAttemptInsert = Database['public']['Tables']['quiz_attempts']['Insert'];
export type QuizAttemptUpdate = Database['public']['Tables']['quiz_attempts']['Update'];

/** Row type for assignments table */
export type AssignmentRow = Database['public']['Tables']['assignments']['Row'];
export type AssignmentInsert = Database['public']['Tables']['assignments']['Insert'];
export type AssignmentUpdate = Database['public']['Tables']['assignments']['Update'];

/** Row type for assignment_submissions table */
export type AssignmentSubmissionRow = Database['public']['Tables']['assignment_submissions']['Row'];
export type AssignmentSubmissionInsert = Database['public']['Tables']['assignment_submissions']['Insert'];
export type AssignmentSubmissionUpdate = Database['public']['Tables']['assignment_submissions']['Update'];

/** Row type for assignment_rubrics table */
export type AssignmentRubricRow = Database['public']['Tables']['assignment_rubrics']['Row'];
export type AssignmentRubricInsert = Database['public']['Tables']['assignment_rubrics']['Insert'];
export type AssignmentRubricUpdate = Database['public']['Tables']['assignment_rubrics']['Update'];
